### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nwhitson** [Roke49/Udacity_P6_V1#1]
Hi!

Looks good, and I like the color coding of the text as the chart items are revealed. Here's a couple thoughts:

Separating the script and the css into different files and linking them in the head would be a good idea. Really helps when keeping track of what's what.

Might be nice to make the colors you chose into variables so you can fiddle with them more easily. Could be a class you add to all those elements that you want to style together.

Might also try putting all your content into a centered container div, which you can center on the page with a width specified (perhaps in percentage?) and margin: 0 auto. Then you can start adapting other things on the page to make them more fluid to fit any size browser window.

With that in mind, I think there's a way to make any .svg element responsive, even the charts, without requiring fancy javascript workarounds to redraw the element. Check out the top answer here: http://stackoverflow.com/questions/16265123/resize-svg-when-window-is-resized-in-d3-js.

I have some thoughts on styling of text, etc., but that's my designer hat on :)

I think the visualization is very clear and successful in conveying the message. All of the above is just suggestions that might help for the next project.

Additional ideas from Nate:
Bold explanatory text as chart is drawn.  Do something (? color) left and right Y axes to make their relationship to the relevant lines in chart clearer.  ? Fade lines on chart as new ones drawn.
Make both heat wave days lines same color.  Reading text hard with long line length, ? 2 columns.
Make whole graphic resizable.

**Comment by Roke49** [comment]
Hi, Nate.
Thank you very much for reviewing my project.  Any designer-hat ideas you
are willing to share would be most appreciated also.  The focus of the
design-review-revise cycle for my Udacity course is supposed to be the
effectiveness of the visualization in telling a story.  So your comments on
things like text styling, color use, etc. would be great also.
See you soon.
Dad
